# Generated by Django 4.1.7 on 2023-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_content_teacher_position_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_code',
            name='code_url',
            field=models.TextField(default='', verbose_name='代码路径'),
        ),
    ]
