# Generated by Django 4.1.7 on 2023-03-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_database_code_code_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_code',
            name='code',
            field=models.TextField(default='', verbose_name='代码名称'),
        ),
    ]
