# Generated by Django 4.1.7 on 2023-03-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_database_code_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_code',
            name='code',
            field=models.FileField(default='python manage.py makemigrations', upload_to='app01/static/media_for_code', verbose_name='代码文件'),
        ),
    ]
